### ISSUE TITLE
Cannot read property 'split' of undefined in Profile.js with GSuite login

### ISSUE THREAD

**Issue by mbalex99** [auth0/passport-auth0#105]
### Description

When using 1.3.1 I am getting an error when a successful login occurs with a GSuite Login. 

```
TypeError: Cannot read property 'split' of undefined
    at new Profile (\node_modules\passport-auth0\lib\Profile.js:9:29)
```

### Reproduction

```ts
passport.use(
  new Auth0Strategy(
    {
      domain: process.env.AUTH0_DOMAIN,
      clientID:
        process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET,
      callbackURL:
        process.env.AUTH0_CALLBACK_URL
    },
    function(_accessToken, _refreshToken, extraParams, profile, done) {
      console.log(profile)
      done(null, profile)
    }
  )
);
```

My routes are as follows: 

```ts
  server.get(
    "/auth0",
    passport.authenticate("auth0")
  );
  server.get(
    "/auth0/callback",
    passport.authenticate("auth0", { successRedirect: '/posts', failureRedirect: "/login" })
  );
  server.get('/login', (req, res) => {
    app.render(req, res, '/login')
  })
  server.get('/logout', (req, res) => {
    req.logOut();
    res.redirect('/login');
  })
```

I see that the authentication is successful, just that this library is getting empty data. If I add console.log in `Profile.js`

```js
function Profile(data, raw) {
  console.log(`data `, data)
  console.log(`raw `, raw)
  // omitted code 
}
```
It will print:

```
data  {}
raw  {}
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.3.1
- **Version of the platform or framework used, if applicable:** Node 12.1.0

**Comment by mbalex99** [comment]
Actually I fixed it I needed to add the scope:

Originally I had:
```ts
server.get(
    "/auth0",
    passport.authenticate("auth0", {scope: ["email"]})
  );
```

Now I have:

```ts
server.get(
    "/auth0",
    passport.authenticate("auth0", {scope: ["openid profile"]})
  );
```

Now data flows through and the parsing does not throw an error.

**Comment by joshcanhelp** [comment]
@mbalex99 - Thank you for the report here. That's definitely related to the latest release (PR #103). Is this in an existing application that was working before or a new one?

**Comment by mbalex99** [comment]
This was a new application. I am not sure if it would have worked with an older version of this library.

**Comment by cbovis** [comment]
I'm seeing this issue as well since upgrading from 1.3.0 to 1.3.1. I'll gather some more info about my specific usage and report back.

**Comment by joshcanhelp** [comment]
Appreciate the information here everyone and apologies for the breakage on a patch release. 

Not having an ID of some kind is a problem and it looks like not including the `openid` scope is leading to that ID being missing. I can't get any meaningful user identity response if I don't include that scope so I'd be curious how an existing app is configured where this is a problem.
