### ISSUE TITLE
Consider releasing 1.3.2 ASAP

### ISSUE THREAD

**Issue by ManBearTM** [auth0/passport-auth0#112]
### Description

Version 1.3.1 has a severe issue that was fixed in https://github.com/auth0/passport-auth0/commit/7879fadee6e2aae0033678dd6a5fc0253d5e90f5 back in december, but over a month later there is still no release. It is very common to use the caret `^` for versioning in `package.json`, which means people will be upgrading to 1.3.1 without them knowing it contains a critical bug.

### Reproduction

Install `passport-auth0@1.3.1` and create a login flow that ultimately calls `handleIdTokenValidation` without any `authParams`.

### Environment

- **Version of this library used:** 1.3.1
- **Version of the platform or framework used, if applicable:** Node 12.14.1

**Comment by joshcanhelp** [comment]
@ManBearTM - Thank you for the ping and apologies for the delay. I'll prioritize getting that out today or tomorrow.

**Comment by joshcanhelp** [comment]
@ManBearTM - Thank you again for reminder here. 1.3.2 out now:

https://www.npmjs.com/package/passport-auth0/v/1.3.2
