### ISSUE TITLE
Allow arbitrary URL parameters for login redirect

### ISSUE THREAD

**Issue by joshcanhelp** [auth0/passport-auth0#113]
### Describe the problem you'd like to have solved

The hosted login page on Auth0 can take a number of parameters not supported by this library. The classic page can also accept arbitrary parameters, which can be used to adjust language, style, and theme of the login page. This library only accepts a certain set of parameters:

https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L91-L125

### Describe the ideal solution

Allow all URL parameters to be added.

### Additional context

See: #111, #64

**Comment by jonah-nestrick** [comment]
Just pinging to keep this issue alive. A PR #117 has been created to address this issue.
