### ISSUE TITLE
Having a session is now required

### ISSUE THREAD

**Issue by homer0** [auth0/passport-auth0#116]
### Description

Before `1.3.0` I could use the middleware without the need of a session:

```js
return passport.authenticate('auth0', {
  audience: '...',
  responseType: 'code',
  connection: '...',
  session: false,
})(req, res, next);
```

But now, due to the changes made on #97 to `Strategy.prototype.authenticate`, if `req.session` is not present, you'll get a `Cannot set property 'authParams' of undefined`.

The real problem here is not that session is required, but that it wasn't released as a breaking change.

### Reproduction

Use the snippet from the description and don't install/use any session library.

### Environment

- **Version of this library used:** `1.3.2`
- **Version of the platform or framework used, if applicable:** `express@4.17.1`
- **Other relevant versions (language, server software, OS, browser):** `node@10.18`

**Comment by afrancht** [comment]
This just took me an hour to figure out! I have been looking everywhere to not use session. This is given me issues as I might want to use a session only temporarily but I then want to authenticate to my API with a JWT not the cookie id.

**Comment by homer0** [comment]
@joshcanhelp Sorry to bother you, but you are the main contributor to the package and I was wondering if you are aware of this issue? it's been more than a month and the issue is not even acknowledged.

**Comment by davidpatrick** [comment]
@homer0 thanks for raising this.  Sorry for the delay here, let me convene with the team and see what we can do about this.
