### ISSUE TITLE
new Auth0Strategy() returns profile, profile does not return app_metadata

### ISSUE THREAD

**Issue by rorycoconnor** [auth0/passport-auth0#118]
```
let strategy = new Auth0Strategy({
  domain: Auth0Config.domain,
  clientID: Auth0Config.clientId,
  clientSecret: Auth0Config.clientSecret,
  callbackURL: Auth0Config.callbackUrl
}, (accessToken, refreshToken, extraParams, profile, done) => {
  // accessToken is the token to call Auth0 API (not needed in the most cases)
  // extraParams.id_token has the JSON Web Token
  // profile has all the information from the user
  
  profile = IdentityProviderUtilities.normalizeAppMetadataOnProfile(profile);
  profile.id_token = extraParams.id_token;
  
  return done(null, profile);
});

```
In this call in our Node app, we expect to get the full user profile object back. However, we never receive the app_metadata. We all have scopes for "users_app_metadata" enabled on the connection in auth0. 
![Screen Shot 2020-04-30 at 4 00 49 PM](https://user-images.githubusercontent.com/31426874/80758832-e284cd80-8afb-11ea-9c3a-3765273468a6.png)

Any idea why we don't get that app_metadata object here?

**Comment by rorycoconnor** [comment]
This is on v.0.6.1

**Comment by rorycoconnor** [comment]
Going to close this out. If anyone runs into this problem, make sure that you have an Auth0 Rule created to expose the app and user metadata.

**Comment by jbrizio** [comment]
@rorycoconnor I have the same error using the v1.3.2! How set the Auth0 Rule to expose those information? Thanks

**Comment by rorycoconnor** [comment]
@jbrizio - Here is a white-labeled screenshot. Essentially, we set up the namespace with our app url and then manually set the keys/values. When you make a call to the UserProfile object, those values should then be exposed. 
<img width="571" alt="Screen Shot 2020-06-01 at 9 17 08 AM" src="https://user-images.githubusercontent.com/31426874/83418132-b5705700-a3e8-11ea-81ac-14267bc7dafa.png">

**Comment by jbrizio** [comment]
@joshcanhelp I can open a pull request to add this scenario into the main doc. What do you think?

**Comment by mike247** [comment]
Was this ever resolved?

**Comment by frederikprijck** [comment]
@mike247 It works as expected, Auth0 doesnt expose those things by default. You can opt in exposing them using a rule as mentioned above.
