### ISSUE TITLE
Documentation link is no longer using this library

### ISSUE THREAD

**Issue by tnguyen14** [auth0/passport-auth0#119]
Your README points to this URL https://auth0.com/docs/quickstart/webapp/nodejs for more documentation and example. However, that example is using `express-openid-connect` instead of `passport-auth0`. 

Is the usage of this library no longer supported/ encouraged?

**Comment by dan-auth0** [comment]
As per our conversation in [Community](https://community.auth0.com/t/node-js-passport-auth0-logout/42430/3), I am raising this internally. Thank you for bringing this up.

**Comment by davidpatrick** [comment]
Thanks @tnguyen14 for the question.  That quickstart has since been reverted.  At this time, no official plans of deprecation have been decided for this library.
