### ISSUE TITLE
Login loop when using multiple frontend instances on the same url

### ISSUE THREAD

**Issue by dm2rsq** [auth0/passport-auth0#123]
I've implemented the Auth0 Node login flow as described here: https://auth0.com/blog/create-a-simple-and-secure-node-express-app/ and it works well, both locally, both when deployed to a dev server inside a Docker container.

However, once I put this into production, I’m stuck in a redirect loop between Auth0 and my page because there is no user instance in my requests, although logs show a successful login. Its because in production, we start up 3 Docker containers with the frontend app. We need this for the resilience and backups. The load balancer distributes the requests among them. If we take production down to 1 container, it works fine. It appears that the Node server needs to be the same one that initiated the login, despite it being on the same url. Is there a way inside Auth0 around it or it does not support multiple server instances?

- Version of this library used: 1.3.3
- Other relevant versions (language, server software, OS, browser): hosted on AWS

**Comment by gianbuono** [comment]
Did you find any workaround? I think i'm facing a similar issue

**Comment by davidpatrick** [comment]
A few questions:

1. Are you using sessions? What is your session configuration?
2. Are you using a shared data store for serializing/deserializing the user?

If you are starting from the blog, you might want to check out our latest library we have just released https://auth0.com/blog/auth0-s-express-openid-connect-sdk/
