### ISSUE TITLE
Usage with Auth0.js checkSession or similar

### ISSUE THREAD

**Issue by yemi** [auth0/passport-auth0#125]
### Description

I have a server side rendered SPA that uses this lib on the server and sometimes needs the id token from Auth0 to call my Hasura API. Is there any way I could use something like auth0.js's `checkSession` to get the token? 

The idea behind `checkSession` is to refresh access tokens inside an iframe in order to not have to leave/refresh the page.

Is it easy to integrate auth0.js with a backend running passport-auth0 or how would i achieve silent auth from the SPA?

**Comment by adamjmcgrath** [comment]
Hi @yemi 

There's no frontend code in this project, what I would suggest is:

- login and get the access token (AT) for your api
- store the AT in your session
- have an api route on your server that gets the AT from the session and uses it to access the API and return the data
- call the API route on your server from your frontend

So your server will effectively proxy the API and supply the AT.

**Comment by yemi** [comment]
Thank you that sums it up! 👍
