### ISSUE TITLE
Discord connection scope override not working

### ISSUE THREAD

**Issue by botv** [auth0/passport-auth0#130]
### Description

Attempting to override the default Discord social connection scope (`identify`) results in a corrupted auth URI. Attempting to add to the scope has the following effect (click the link to see the problem): 

[`https://discordapp.com/api/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fmeta-labs.us.auth0.com%2Flogin%2Fcallback&scope=identify%20email%20guilds.join%2Cidentify&state=4Gs_bHHSYydzucR7YrDlv5dyn9Mg_MK7&client_id=648234176805470248`](https://discordapp.com/api/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fmeta-labs.us.auth0.com%2Flogin%2Fcallback&scope=identify%20email%20guilds.join%2Cidentify&client_id=648234176805470248)

Notice the scope, `identify%20email%20guilds.join%2Cidentify`, which translates to `identify email guilds.join,identify`. The correct format is to have scopes separated by spaces, but Auth0 incorrectly assumes that a comma should be used.

### Reproduction

1. Configure the application to use the Discord social connection:

![Screen Shot 2020-10-01 at 11 09 22 PM](https://user-images.githubusercontent.com/29611437/94884318-2711ed80-043b-11eb-82c4-7d48d4cea695.png)

2. Set the following Passport Auth0 strategy:

```js
const auth0Strategy = new Auth0Strategy(
  {
    domain: process.env.AUTH0_DOMAIN,
    clientID: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    callbackURL: process.env.AUTH0_CALLBACK_URL || 'http://localhost:7000/ajax/auth/callback',
  },
  ((accessToken, refreshToken, extraParams, profile, done) => {
    console.log(profile);
    return done(null, profile);
  }),
);
```

3. Set up the auth routes:

```js
router.get('/auth', passport.authenticate('auth0', {
  connection: 'discord',
  connection_scope: 'identify email guilds.join',
}));

router.get('/auth/callback', passport.authenticate('auth0', {
  connection: 'discord',
  connection_scope: 'identify email guilds.join',
  failureRedirect: '/login',
}), (req, res) => {
  res.redirect('/');
});
```

### Environment

- **Version of this library used:** v1.3.3
- **Version of the platform or framework used, if applicable:** Node v14.9.0
- **Other relevant versions (language, server software, OS, browser):** Node, Express
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by davidpatrick** [comment]
Hey @botv thanks for raising the issue, we will take a look and see what is going on

**Comment by davidpatrick** [comment]
@botv this appears to be happening on the Auth0 server side.  Passport is passing the correct encoding of `connection_scope` to Auth0 url, but the redirect from the Auth0 server to Discord seems to be trying to join the `connection_scope` with `scope` and making `identify email guilds.join,identify`.  I will reach out to the team that maintains this connection and see if we can get to the bottom of this.

**Comment by botv** [comment]
@davidpatrick any update on this?

**Comment by davidpatrick** [comment]
Hey @botv I just got back from vacation today, sorry for the delay.  It looks like our authorize endpoint currently accepts comma delimited  lists for `connection_scope` as documented here https://auth0.com/docs/connections/adding-scopes-for-an-external-idp#2-pass-scopes-to-authorize-endpoint

I am waiting for clarification from the team on supporting this space delimited lists, which is what Discord is expecting.

**Comment by botv** [comment]
Sounds great, and thanks so much for the support. Any idea how soon we'll hear about this? We're waiting on this patch to switch to Auth0, Discord doesn't support wildcard redirects so the faster we can get this fixed the better.

**Comment by davidpatrick** [comment]
Okay @botv it looks like you will need to patch the connection through the Auth0 Management API.  You can do this directly through the documentation https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id the id will be your connection identifier `con_dZGkZnKPGP1ZzBt7` and your payload will look something like (set the client creds):

```
{
  "options": {
    "scripts": {
      "fetchUserProfile": "function fetchUserProfile(accessToken, context, callback) {\n  request.get({\n    url: 'https://discordapp.com/api/users/@me',\n    headers: {\n      'Authorization': 'Bearer ' + accessToken\n    }\n  },\n  (err, resp, body) => {\n    if (err) {\n      return callback(err);\n    }\n\n    if (resp.statusCode !== 200) {\n      return callback(new Error(`[Response code: ${resp.statusCode}] ${body}`));\n    }\n\n    let bodyParsed;\n    try {\n      bodyParsed = JSON.parse(body);\n    } catch (jsonError) {\n      return callback(new Error(body));\n    }\n\n    return callback(null, bodyParsed);\n  });\n}"
    },
    "icon_url": "https://cdn.auth0.com/marketplace/catalog/content/assets/creators/discord/discord-avatar.png",
    "tokenURL": "https://discordapp.com/api/oauth2/token",
    "client_id": "", // set your client id
    "client_secret": "", // set your client secret
    "authorizationURL": "https://discordapp.com/api/oauth2/authorize",
    "integration_name": "discord"
  }
}
```

You can verify it has the correct scope by retrieving the connection through https://auth0.com/docs/api/management/v2#!/Connections/get_connections_by_id
