### ISSUE TITLE
Request is deprecated

### ISSUE THREAD

**Issue by KenEucker** [auth0/passport-auth0#137]
https://github.com/request/request/issues/3142

Request has been deprecated. Can we get an update to replace this dependency?

**Comment by frederikprijck** [comment]
Thanks, that is not an unfair request.

However, given the fact that, as mentioned on our readme, https://github.com/auth0/express-openid-connect is given favor over `passport-auth0`, we will have a look at how we want to proceed with the deprecation of request`` in terms of `passport-auth0`.

**Comment by KenEucker** [comment]
@frederikprijck my apologies, there it is staring me right in the face.

To be honest with you, and this is a compliment, I didn't have to read the documentation.

Passport middlewares follow a great pattern and I've been really happy with the ability to just pick up and use new strategies without having to deep dive into the specific nuances between the strategies. Maybe this is why some people are anti-passportjs, because it makes it too easy to not know what you're getting into?

I am addressing several packages this week that are still using `request`, as they are present in one of my projects. If I submitted a PR to replace `request` with `got`, would that be of interest?

**Comment by frederikprijck** [comment]
What would be your proposal as an alternative? We have replaced request previously, both with axios as well as using node internals and have noticed that it needs some effort to not break users because request covers some proxy specific edge-case things by default, that other libraries might not cover by default. 
E.g. https://github.com/auth0/node-jwks-rsa/issues?q=is%3Aissue+axios

**Comment by KenEucker** [comment]
@frederikprijck I mentioned `got`:
https://github.com/sindresorhus/got

As it is the package I am using in my own projects to replace `request`. This is my first time using it so I can't speak to edge cases at this time.
