### ISSUE TITLE
Please, provide a TypeScript definition file for passport-auth0

### ISSUE THREAD

**Issue by jamesxv7** [auth0/passport-auth0#14]
I tried to search for a .d.ts file for this library but there is nothing available yet. I'm working on a TypeScript based project and a .d.ts file will be a great addition to proper use the library. Is there any possibility to provide this type definition file?

**Comment by r-k-b** [comment]
I've just forked `passport-auth0` to add an `index.d.ts` file: <https://github.com/r-k-b/passport-auth0/tree/typescript-def>.

It's copied almost verbatim from [@types/passport-facebook](https://www.npmjs.com/package/@types/passport-facebook), and I haven't gone through it rigorously so there may be issues. I'll submit a PR when I'm more confident that it's correct.

**Comment by johnbendi** [comment]
@r-k-b what's the status of your fork?

**Comment by r-k-b** [comment]
@johnbendi I haven't been back to that project since January... any contributions would be welcomed.

I just merged in the changes from upstream, if that helps at all.
