### ISSUE TITLE
Please upgrade axios to >1.6.0

### ISSUE THREAD

**Issue by FauxFaux** [auth0/passport-auth0#175]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/passport-auth0#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/passport-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

There's a security vulnerability in axios 0.x and 1.x < 1.6.

This library depends on axios 0.27:
https://github.com/auth0/passport-auth0/blob/25d266112df8d3a78df00145e7cebe642c2227ea/package.json#L20

### Describe the ideal solution

Please move to an http client without a vuln, easiest is probably axios 1.6.0.

**Comment by frederikprijck** [comment]
Thanks, will look into updating this.

**Comment by frederikprijck** [comment]
Opened a PR, but needs some additional testing from our side just to ensure everything works as expected.

Given the limited use of axios, I do not expect any issues.

Feel free to also give this a test to help speed things up.

**Comment by frederikprijck** [comment]
Released as 1.4.4

**Comment by FauxFaux** [comment]
Haha, resolved before I'd finished reading the list of affected packages. Great work. :)

**Comment by Bharts8** [comment]
Perhaps this should have been a minor change due to axios moving from commonJS to ES between these two versions. Maybe it is not relevant, but we did see some legacy stuff fall over after pulling 1.4.4 so leaving this comment for posterity.

**Comment by frederikprijck** [comment]
I looked into this, and was not able to reproduce this. Would appreciate some more information to help understand scenario's where this would break.

What I did was, i took [this project](https://github.com/auth0-blog/wab-portal-express), and migrated it to use the latest version of passport-auth0 and was still able to successfully run the application and use the SDK, include the deprecated method that actually uses axios.

**Comment by Bharts8** [comment]
Yea after a little more digging there are other issues that really exacerbated that legacy stuff. The reliance on a completely outdated node version was probably the more sinister culprit that just exposed this the underlying import in pasport-auth0 which blew out for us. 

I don't think you need to specifically do anything (though it'd be interesting to see if there WERE any breaking changes between a 0.X and a 1.X just in case, but it doesn't seem like it). At this point this is more so just putting in a comment for the next person who comes sniffing if their builds start coughing, giving them someplace to look at.
