### ISSUE TITLE
Link for complete example points at the same page

### ISSUE THREAD

**Issue by jzaefferer** [auth0/passport-auth0#19]
Under https://github.com/auth0/passport-auth0#complete-example there is a [here](http://github.com/auth0/passport-auth0) link, which just points at the same page. I didn't find a complete example anywhere in this repo.

If there is none, the link should be removed. Better yet to point to an actual full example.

**Comment by ebourmalo** [comment]
:+1:

**Comment by tejasmanohar** [comment]
:+1:

**Comment by ddbaron** [comment]
:+1:

**Comment by bendiy** [comment]
Fixed by: https://github.com/auth0/passport-auth0/pull/79/files#diff-04c6e90faac2675aa89e2176d2eec7d8R116

**Comment by bendiy** [comment]
That example doesn't work anymore. It's from 2016. The CORS changes in 2018 completely break it. Auth0 seems to be pushing the Universal Login vs. embedded now. This example works and uses `passport-auth0`:
* https://github.com/auth0-samples/auth0-nodejs-webapp-sample/tree/master/01-Login
