### ISSUE TITLE
Use specific error classes instead of Error

### ISSUE THREAD

**Issue by rolodato** [auth0/passport-auth0#20]
For example: https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L160-L171

Currently we're just using plain `Error`: https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L115

**Comment by cyxou** [comment]
+1
I would like to redirect blocked users to a separate page with some information for them why they were blocked. Is that possible?

**Comment by dshorowitz** [comment]
+1 also. Especially if this could be used in combination with errors coming from auth0 rules

**Comment by joshcanhelp** [comment]
Apologies for the very late response here. 

We definitely need to address error handling in this strategy. I'll leave this open and look into the best way to handle this going forward.
