### ISSUE TITLE
Get JWT token for user

### ISSUE THREAD

**Issue by tejasmanohar** [auth0/passport-auth0#25]
[here](https://auth0.com/blog/2015/04/09/adding-authentication-to-your-react-flux-app/, it says
>Auth0 issues JSON Web Tokens on every login for your users.

Once the user authenticates via Passport Auth0, how do you get their JWT token? I see that `req.user` contains a key `sub` so it looks like this may be the payload of the JWT (?) but not sure how to find the actual token.

**Comment by tejasmanohar** [comment]
Nvm, haha - my bad

https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L92

**Comment by larzKke** [comment]
Hi tejasmanohar, 
I'm have the same issue. 
How can I access to the `id_token` anywhere in my app when the user is logged in?

```
var strategy = new Auth0Strategy({
    domain:       'foo.eu.auth0.com',
    clientID:     'xxxxxxxxx',
    clientSecret: 'xxxxxxxx',
    callbackURL:  '/login'
  }, function(accessToken, refreshToken, extraParams, profile, done) {
    // accessToken is the token to call Auth0 API (not needed in the most cases)
    // extraParams.id_token has the JSON Web Token
    // profile has all the information from the user
    var id_token = extraParams.id_token;
    return done(null, profile, id_token);
  });
```

**Comment by tejasmanohar** [comment]
Not sure. Maybe it needs to be integrated w/ middleware.

**Comment by alexb-uk** [comment]
In case anyone else comes across this post looking for a way to get hold of id_token see below. NOTE: I'm no passport or Auth0 expert so use with caution!

Taking @larzknoke example code, note that the third parameter of done() goes into req.authInfo.
```javascript
var strategy = new Auth0Strategy({
    domain:       'foo.eu.auth0.com',
    clientID:     'xxxxxxxxx',
    clientSecret: 'xxxxxxxx',
    callbackURL:  '/login'
  }, function(accessToken, refreshToken, extraParams, profile, done) {
    // accessToken is the token to call Auth0 API (not needed in the most cases)
    // extraParams.id_token has the JSON Web Token
    // profile has all the information from the user
    var id_token = extraParams.id_token;
    return done(null, profile, id_token);
  });
```

Get hold of id_token via req.authInfo:
```javascript
app.get(
  `/callback`,
  passport.authenticate('auth0', {
    failureRedirect: `/login`,
  }),
  (req, res) => {
    if (!req.user || !req.authInfo) {
      throw new Error('user not authenticated');
    }

    const expiresIn = 1000 * 60 * 60 * 24 * 180; // 180 days

    res.cookie('id_token', req.authInfo, {
      maxAge: expiresIn,
      httpOnly: true,
      secure: !__DEV__,
    });
    res.redirect(`/`);
  },
);
```

*\_\_DEV__ can be replaced with true if you don't disable HTTPS during development.

**Comment by skoldborg** [comment]
Just a quick recommendation note to the above code. You should never store a users complete JWT in a session as this makes it easily available to the public. If you need to store some identifying info you can extract some unique but harmless identifier, such as the user's email, and store that in a cookie.

**Comment by alexb-uk** [comment]
Hi @skoldborg,

Could you elaborate on where you think there is a security hole in storing JWT's in cookies?
Do you mean access_tokens, id_tokens or both?

AFAIK it's completely secure given you protect against CSRF, set httpOnly and the secure flag.

e.g. https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by alexb-uk** [comment]
Hi @skoldborg,

Could you elaborate on where you think there is a security hole in storing JWT's in cookies?
Do you mean access_tokens, id_tokens or both?

AFAIK it's completely secure given you protect against CSRF, set httpOnly and the secure flag.

e.g. https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by skoldborg** [comment]
@alexb-uk Might be that I'm missing some part, I'm certainly no expert in how passport-auth0 works, but where is the protection against CSRF set up?

**Comment by alexb-uk** [comment]
CSRF would be outside the scope of passport-auth0.

For example for Express-JS you might look at: https://github.com/expressjs/csurf#using-ajax
