### ISSUE TITLE
Login page loop

### ISSUE THREAD

**Issue by RickEyre** [auth0/passport-auth0#26]
When I login it just goes back to the login page on auth0. The auth0 strategy function never gets called. What could be happening?

```js
var strategy = new Auth0Strategy({
   domain:       'your-domain.auth0.com',
   clientID:     'your-client-id',
   clientSecret: 'your-client-secret',
   callbackURL:  '/callback'
  },
  function(accessToken, refreshToken, extraParams, profile, done) {
    console.log('never gets called');
    return done(null, profile);
  }
);
```

I've verified that my callback is called from auth0, however.

**Comment by jfromaniello** [comment]
Can you show your routes logic?

**Comment by RickEyre** [comment]
It was exactly like your code in the README. I finally got it working following [this](https://auth0.com/docs/server-platforms/nodejs) article though. Thanks!
