### ISSUE TITLE
Specify JWT scope

### ISSUE THREAD

**Issue by BobbyKostadinov** [auth0/passport-auth0#29]
Hey

Is there a way to specify the scope for JWT in order to include more details from the id_token ?

Thanks

**Comment by burton-scalefastr** [comment]
I think it has to go into the authenticate call:

```javascript
    passport.authenticate('auth0', {
        clientID: conf.AUTH0.CLIENT_ID,
        domain: conf.AUTH0.DOMAIN,
        redirectUri: conf.AUTH0.CALLBACK_URL,
        audience: 'https://' + conf.AUTH0.DOMAIN + '/userinfo',
        responseType: 'code',
        scope: 'openid profile user_metadata app_metadata'
    }),
```

**Comment by joshcanhelp** [comment]
For anyone looking for this now ... the sample above is correct in terms of where scopes go. These must be [OIDC standard scopes](https://auth0.com/docs/scopes/current/oidc-scopes), which `user_metadata` and `app_metadata` are not. If you need data outside of the standard scopes, you'll need to add [custom claims](https://auth0.com/docs/scopes/current/custom-claims).
