### ISSUE TITLE
JWT Token

### ISSUE THREAD

**Issue by ghost** [auth0/passport-auth0#30]
In [readme](https://github.com/auth0/passport-auth0/blob/master/README.md) it's said that

> extraParams.id_token has the JSON Web Token

but I can't figure it out. I need to take the JWT token of the user with profile but I can't figure out how to do it. Any help will be appreciated

**Comment by asharifi** [comment]
```javascript
var strategy = new Auth0Strategy({
    domain: process.env.AUTH0_DOMAIN,
    clientID: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    callbackURL: "/auth0callback"
},
    function (accessToken, refreshToken, extraParams, profile, done) {
        console.log(extraParams.id_token);
        return done(null, profile);
    });
```
Output: undefiend

**Comment by mikemimik** [comment]
@asharifi the `id_token` is only present when the `responseType` is set to `code` when sending the initial request to the api.

**Comment by asharifi** [comment]
@mikemimik  thanks for reply. So what should I change/add to my library to be able to get that in the function??

**Comment by mikemimik** [comment]
@asharifi in your application, I'm making the assumption that you have the user login on some route `/login` where they are presented with a login form/modal. Assuming again, on this page, you are using the [`lock`](https://github.com/auth0/lock) library. Then in the `options` variable given to the constructor of `Auth0Lock` you would need to have something like the example below.
```javascript
var lock = new Auth0Lock('{{clientID}}', '{{domain}}', {
  auth: {
    responseType: 'code',
    redirectUrl: '{{callbackUrl}}'
  }
});
lock.show();
```
> Where {{clientID}} is the clientID of the application you're using with auth0 (eg: `EDSHwerwk2l1kjf`), {{domain}} is the tenant domain you're using with auth0 (eg: `mycompany.auth0.com`), and {{callbackUrl}} is a white listed callback url you have added to the client you're using on auth0 (eg: `http://localhost:3000/callback`)

> In the above example I've also assumed that you're using a templating language that usings handlebars (`{{`, `}}`) to wrap view model variables.

**Comment by KidkArolis** [comment]
Having the same issue, docs are not accurate

**Comment by KidkArolis** [comment]
Had to pass `scope` param to `passport.authenticate`:

```js
passport.authenticate('auth0', { scope: 'openid', failureRedirect: '/' }),
```

**Comment by KidkArolis** [comment]
Looks like the docs are indeed incomplete?
