### ISSUE TITLE
Incompatible with Lock for Web's responseMode option

### ISSUE THREAD

**Issue by jcw-** [auth0/passport-auth0#39]
The usage of `req.query` (https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L61) makes this strategy incompatible with the `responseMode` option of Lock for Web: https://auth0.com/docs/libraries/lock/v10/customization#responsemode-string-

Ideally this would work with both!

Workaround: Don't use `responseMode` and let the callback over via `GET`

**Comment by joshcanhelp** [comment]
We recommend using the Universal Login Page for authentication. [See our docs for a comparison](https://auth0.com/docs/guides/login/universal-vs-embedded).
