### ISSUE TITLE
Generalize this! (not a movie) ;)

### ISSUE THREAD

**Issue by johnkors** [auth0/passport-auth0#4]
Hi, just a question. While I understand it from your companys view, why not write a OpenId Connect provider instead of a Auth0 specific provider. Using the discovery endpoint and so on, instead of hard coded paths to Auth0 specific urls.

That would be of more use to the community I think. Then it could be used towards any OpenId Connect provider. Or do you think most OpenId Connect providers differ to much (even though there is a standard), that  it would be hard to maintain?

**Comment by jfromaniello** [comment]
You probably mean this one from @jaredhanson : 

https://github.com/jaredhanson/passport-openidconnect

**Comment by jfromaniello** [comment]
It would be great to support discovery there :)
