### ISSUE TITLE
"JavaScript heap out of memory" in /qs/lib/parse.js:70

### ISSUE THREAD

**Issue by dynnamitt** [auth0/passport-auth0#45]
<--- Last few GCs --->
312876625 ms: Mark-sweep 1269.1 (1403.1) -> 1269.0 (1403.1) MB, 1083.5 / 0.0 ms [allocation failure] [GC in old space requested].
312877702 ms: Mark-sweep 1269.0 (1403.1) -> 1269.0 (1403.1) MB, 1076.6 / 0.0 ms [allocation failure] [GC in old space requested].
312878768 ms: Mark-sweep 1269.0 (1403.1) -> 1269.0 (1403.1) MB, 1065.8 / 0.0 ms [last resort gc].
312879862 ms: Mark-sweep 1269.0 (1403.1) -> 1269.0 (1403.1) MB, 1093.1 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x1c15735cfb39 <JS Object>
1: parseObjectRecursive(aka parseObjectRecursive) [/app/node_modules/qs/lib/parse.js:70] [pc=0x10322d72d146] (this=0x1c1573504381 <undefined>,chain=0x3eb84daef901 <JS Array[0]>,val=0x3eb84daefd51 <String[7]: polling>,options=0x3eb84daf0479 <an Object with map 0x14ff9e204ba1>)
2: parseQueryStringKeys(aka parseQueryStringKeys) [/app/node_modules/qs/lib/parse.js:129] [pc=0x10322d72c286] (t...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
1: node::Abort() [node]
2: 0x109b7ac [node]
3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
5: v8::internal::Factory::NewTransitionArray(int) [node]
6: v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [node]
7: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Handle<v8::internal::LayoutDescriptor>, v8::internal::TransitionFlag, v8::internal::MaybeHandle<v8::internal::Name>, char const*, v8::internal::SimpleTransitionFlag) [node]
8: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [node]
9: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::Representation, v8::internal::TransitionFlag) [node]
10: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [node]
11: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [node]
13: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
12: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
14: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
15: v8::internal::KeyedStoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
16: v8::internal::Runtime_KeyedStoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [node]
17: 0x10322d2092a7
Aborted
No newer events found at the moment. Retry.

**Comment by dynnamitt** [comment]
Problem is lib qs ... maybe an idea to use newer request (2.81.0) not 2.61.0  ??

**Comment by dynnamitt** [comment]
Starting a LONG RUNNING TEST on AWS now with latest request+qs  .....

**Comment by ljharb** [comment]
https://github.com/ljharb/qs/issues/211#issuecomment-306412774
> This looks like a malformed request, and an absence of a "limit" - can you provide the JS code that's invoking `qs.parse`?

**Comment by dynnamitt** [comment]
It's not so easy to find for me since I am (atleast) 3 layers above qs. It might come from a passport.deserialize() call..
