### ISSUE TITLE
throw new Error('You must provide the ' + k + ' configuration value to use passport-auth0.');

### ISSUE THREAD

**Issue by alaguraj448** [auth0/passport-auth0#47]
throw new Error('You must provide the ' + k + ' configuration value to use passport-auth0.');

**Comment by hokakede1** [comment]
have you find out the solution ?

**Comment by wordaddict** [comment]
I am having this same issue, same bug

**Comment by craask** [comment]
I also ran into this issue. Will code around and see if I can fix it.

**Comment by oldtinroof** [comment]
Have you set the Strategy properly in your app initialisation?

Checkout https://github.com/auth0/passport-auth0/blob/master/lib/index.js#L31 - it shows that you're going to need all your Auth0 details in the strategy:

`// Configure Passport to use Auth0
const strategy = new Auth0Strategy(
  {
    domain: process.env.AUTH0_DOMAIN,
    clientID: process.env.AUTH0_CLIENT_ID,
    clientSecret: process.env.AUTH0_CLIENT_SECRET,
    callbackURL: process.env.AUTH0_CALLBACK_URL,
  },
  (accessToken, refreshToken, extraParams, profile, done) => done(null, profile));

passport.use(strategy);`

**Comment by ms-vague** [comment]
I'm having the same trouble with this error and not sure how to fix it.

**Comment by KShewengerz** [comment]
Had encountered this problem when on my Auth0 strategy callback - had named mine in camelCase **"callbackUrl"** where it should be **callbackURL**, then it works.

**Comment by siamraj** [comment]
Directly write domain,clientID,clientSecret and callbackurl. It's working fine . 

const strategy = new Auth0Strategy(
  {
    domain: "test.auth0.com",
    clientID: "sdfsdfsdfsdf",
    clientSecret: "sfsdfsdf-sdfsdfsdfsdf",
    callbackURL: 'http://localhost:3000/callback'
  },
  function(accessToken, refreshToken, extraParams, profile, done) {
    // accessToken is the token to call Auth0 API (not needed in the most cases)
    // extraParams.id_token has the JSON Web Token
    // profile has all the information from the user
    return done(null, profile);
  }
);

**Comment by thirsch7** [comment]
I had the same issue, and what solved it for me was moving `dotenv.config()` above where you create your strategy. Siamraj's comment will also work because it circumvents the need for the information from your .env file, but `dotenv.config()` is what allows you to read from your .env file.

**Comment by jithin-zachariah** [comment]
change the filename of .env.example to just .env
