### ISSUE TITLE
user_id is missing in profile

### ISSUE THREAD

**Issue by uschmann** [auth0/passport-auth0#48]
Hi,

i just did the nodejs/express quickstart for auth0.
It seems like the user_id property is missing in req.user after a use authenticated.

```javascript
const strategy = new Auth0Strategy(
  {
    domain: '',
    clientID: '',
    clientSecret: '',
    callbackURL: process.env.AUTH0_CALLBACK_URL || 'http://localhost:3000/callback',
    scope: 'openid profile email'
  },
  function(accessToken, refreshToken, extraParams, profile, done) {
    console.log(profile.user_id);   // This is undefined
    return done(null, profile);
  }
);
```

The docs about the profile clearly states that user_id is always available in the normalize profile:
https://auth0.com/docs/user-profile/user-profile-details#normalized-user-profile

This is what i get when i print out the profile object:

```javascript
{
  "displayName": "Andre Uschmann",
  "name": {
    "familyName": "Uschmann",
    "givenName": "Andre"
  },
  "picture": "https://lh5.googleusercontent.com/-KymPmQzSHZA/AAAAAAAAAAI/AAAAAAAAAAA/CSvKv_F1Xy8/photo.jpg",
  "locale": "de",
  "nickname": "andre.uschmann",
  "gender": "male",
  "_json": {
    "sub": "google-oauth2|116203000818893399355",
    "name": "Andre Uschmann",
    "given_name": "Andre",
    "family_name": "Uschmann",
    "nickname": "andre.uschmann",
    "picture": "https://lh5.googleusercontent.com/-KymPmQzSHZA/AAAAAAAAAAI/AAAAAAAAAAA/CSvKv_F1Xy8/photo.jpg",
    "gender": "male",
    "locale": "de",
    "updated_at": "2017-08-02T06:45:28.070Z"
  },
  "_raw": "{\"sub\":\"google-oauth2|116203000818893399355\",\"name\":\"Andre Uschmann\",\"given_name\":\"Andre\",\"family_name\":\"Uschmann\",\"nickname\":\"andre.uschmann\",\"picture\":\"https://lh5.googleusercontent.com/-KymPmQzSHZA/AAAAAAAAAAI/AAAAAAAAAAA/CSvKv_F1Xy8/photo.jpg\",\"gender\":\"male\",\"locale\":\"de\",\"updated_at\":\"2017-08-02T06:45:28.070Z\"}"
}
```

It seems like the user_id is stored in profile._json.sub?
But this is nowhere mentioned in the docs.

Am i missing something?

**Comment by carchrae** [comment]
it think this is actually a bug deep inside auth0 - they have not normalized the property `sub` correctly. 

there is no id property anymore:  (since 2015 it seems)

https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo

more details here: https://stackoverflow.com/questions/8311836/how-to-identify-a-google-oauth2-user

**Comment by carchrae** [comment]
anyway, @uschmann - if you want to use my fixed version, replace the dependency in package.json with 

```
"passport-auth0": "git@github.com:FrontierFoundry/passport-auth0.git"
```

**Comment by ildella** [comment]
I have the same issue. I get an additional field after displayName, "id: undefined".

**Comment by carchrae** [comment]
@ildella - in my version it is `id`.  you're right that this is also confusing as the normalized profile is `user_id`

**Comment by carchrae** [comment]
i take that back - something else must be wrong in your case: https://github.com/FrontierFoundry/passport-auth0/commit/730df9ced29c33989a1e06f330294031820c02f8

**Comment by ildella** [comment]
the strange thing is that calling directly the API https://auth0.com/docs/api/authentication?shell#get-user-info using a fresh and working accessToken, I get that response properly filled but both user_id and sub are not present. Does that API works for you?

**Comment by carchrae** [comment]
i think it may depend on what auth method you are using - also if the person is signed up.  i am just guessing.  i don't use this method anymore and i don't work for auth0, so you may want to take it up with them.  i do feel you pain though, we spent a lot of time to get auth0 working - too many differing docs and apis make it hard to use.

**Comment by ildella** [comment]
what you mean with this method? I am using passport-js auth0 strategy, and I've enabled facebook and google. Is basically what is in their quickstart for web apps (non SPA). I'm not using and alternate method, but the official one :)
The authentication API or nodejs client are performing the same call and return the same stuff.. seem just plain broken or I am doing something wrong that do NOT alter the rest of the behavior. In fact users are being signed up, are in the DB etc...

**Comment by rjsteinert** [comment]
Hi @carchrae and @ildella - Just getting started with this myself and ran into this bug. Is this module not maintained? I see there hasn't been commits since 2016. It appears that Auth0 is still in business. What do y'all think they would suggest using if not this module?

**Comment by carchrae** [comment]
yeah, unsupported modules look bad. @auth0 @hzalaz  - are you guys still out there?  is this dead?  deprecate or put a link to what people should use.  i guess they don't actually support passport.js

**Comment by luisrudge** [comment]
Hi folks! I'm Luis from Auth0. Sorry we let you guys alone in this one. I'm not familiar with this project but I'll help move this forward. Just so we are clear, the issue here is that we're not exposing the `user_id` property, although we do expose the non-standard `id`. Is that it? does this PR solves this issue? https://github.com/auth0/passport-auth0/pull/49

**Comment by luisrudge** [comment]
fixed in 0.6.1! Sorry about the bumps, folks! We're discussing internally if we either move this project forward or start recommending another project for OIDC clients. I'll let you know.

**Comment by carchrae** [comment]
thanks luis.  

fwiw, we are not using this anymore: https://www.npmjs.com/package/passport - although it is still a very popular module.

**Comment by aaguiarz** [comment]
Hi @carchrae, can you let us know what are you currently using, so we can keep it in our radar?

Thanks

**Comment by carchrae** [comment]
we use https://github.com/auth0/express-jwt but also use our own middleware as a fallback which calls the auth0 rest api to fetch user details.

**Comment by rjsteinert** [comment]
@luisrudge I'm all for whatever has me spending less time on building out auth in my application, more time building what makes my app special. Seems like quite the business opportunity for auth0. `passport-auth0` seemed like the easiest thing in all of the node-verse but perhaps `auth0/express-jwt` is easy? @carchrae Any walkthroughs or example codebases you would recommend?
