### ISSUE TITLE
profile is empty after succesfull authentication

### ISSUE THREAD

**Issue by ildella** [auth0/passport-auth0#52]
Hi. Everything works but the profile i receive is almost empty, looks like this:

`Profile {
  displayName: undefined,
  id: undefined,
  name: { familyName: undefined, givenName: undefined },
  _json: {},
  _raw: '{}' }`

I was using passportjs with google-oauth2 and facebook strategies and works good with profile properly filled. 
In the Auth0 dashboard everything looks good. 

What can I try to make this work? Thanks.

**Comment by tuxounet** [comment]
Hi, i had the same issues
As this documentation : https://auth0.com/docs/quickstart/webapp/nodejs/02-user-profile , add "profile" to scope after openid in your login route : 

```
router.get(
        '/login',
        passport.authenticate('auth0', {
            clientID: config.Auth0_CLIENT_ID,
            domain: config.Auth0_DOMAIN,
            redirectUri: config.Auth0_CALLBACK_URL, 
            audience: 'https://' + env.AUTH0_DOMAIN + '/userinfo',
            responseType: 'code',
            scope: 'openid profile'
        }),
        function (req, res) {
            res.redirect('/');
        }
    ); 

```

Cheers
