### ISSUE TITLE
Passing hosted login page config through to Auth0?

### ISSUE THREAD

**Issue by oldtinroof** [auth0/passport-auth0#53]
Does anyone know how to use this strategy and pass config options to the hosted login page? 

I'd like to set the initialScreen ([as per the docs](https://auth0.com/docs/libraries/lock/v10/configuration#initialscreen-string-)), but can't seem to get that working. This is what I'd expect to work:

```router.get(
  '/signup',
  passport.authenticate('auth0', {
    audience: `https://${env.AUTH0_DOMAIN}/userinfo`,
    responseType: 'code',
    scope: 'openid profile',
    initialPage: 'signUp',
  }),
  (req, res) => {
    res.redirect('/');
  });
```

I've seen a number of requests in the Community pages about this, but the responses have been fairly generic and point to documentation about the Lock & [hosted login page](https://auth0.com/docs/hosted-pages/login), so I thought I'd try here.

**Comment by yaducam** [comment]
Hello,

I would also be interested in having the "initialScreen" option supported :
I would like to force lock to start on the "signup" page when i know a user subscribe for the first time (default lock behaviour is to display the "login" screen).
 
Looking at index.js code, it seems that only "prompt", "audience" and "connexion" options are supported :

`
if (options.connection && typeof options.connection === 'string') {
 params.connection = options.connection;
  }
  if (options.audience && typeof options.audience === 'string') {
    params.audience = options.audience;
  }
  if (options.prompt && typeof options.prompt === 'string') {
    params.prompt = options.prompt;
  }

`
I naively tried to add :

  if (options.initialScreen && typeof options.initialScreen === 'string') {
    params.initialScreen = options.initialScreen;
  }

.. but it didn't help.. Anybody knows how to add this option ?

**Comment by wurde** [comment]
This is a great feature request. With Auth0 only supporting a single "Hosted" login page it'd be nice to pass in the `initialScreen` as an option. A better solution would be supporting an extraParams that can handle custom key values to improve customizing the Hosted page for those trying to use Universal Login.

Hey Jared Hanson, could you take a look at this?

**Comment by jamesryan83** [comment]
You can override the authorizationParams function in your own code before creating an instance of Auth0Strategy.  Better than editing the source I guess.  Like this...
    
    Auth0Strategy.prototype.authorizationParams = function (options) {
        var options = options || {};

        var params = {};
        if (options.connection && typeof options.connection === 'string') {
            params.connection = options.connection;
        }
        if (options.audience && typeof options.audience === 'string') {
            params.audience = options.audience;
        }
        if (options.prompt && typeof options.prompt === 'string') {
            params.prompt = options.prompt;
        }

        // *** This is the option for setting the signup screen as the start screen ***
        if (options.initialScreen && typeof options.initialScreen === 'string') {
            params.initial_screen = options.initialScreen;
        }

        return params;
    }

    var strategy = new Auth0Strategy({
        domain: "DOMAIN",
        clientID: "CLIENT_ID",
        clientSecret: "SECRET",
        callbackURL: "http://localhost:8000/auth-callback"
    }, function (accessToken, refreshToken, extraParams, profile, done) {
        return done(null, profile);
    });

    passport.use(strategy);

And then you can use it like this...

    router.get("/register", passport.authenticate("auth0", { failureRedirect: "/", initialScreen: "signUp" }), auth.register.bind(this));

    router.get("/login", passport.authenticate("auth0", { failureRedirect: "/" }), auth.login.bind(this));

There's probably a neater way to do this, but it seems to be working for me so far.

**Comment by OtavioCapila** [comment]
Do we have any solution for this, or we still need this workaround?

**Comment by naren-bellala** [comment]
Any solution for this yet?

**Comment by frederikprijck** [comment]
Custom parameters should be possible to be sent now that https://github.com/auth0/passport-auth0/pull/131 is merged.

This would allow you to use something like this:

```
passport.authenticate('auth0', {initial_screen : '...'}), 
```

Next you will need to configure the lock side as mentioned in https://github.com/auth0/passport-auth0/issues/53#issuecomment-379463280
