### ISSUE TITLE
Custom User Store vs Auth0 Database

### ISSUE THREAD

**Issue by tim-soft** [auth0/passport-auth0#54]
I have an app with a working login flow against an Auth0 User-Password Database. If I change the database connection to custom database in the Auth0 dashboard, `req.user` no longer gets set in express despite a successful authentication.

Is there anything that would need to be changed to passport for using a custom database connection?

**Comment by joshcanhelp** [comment]
There should not be anything special that needs to be done in this strategy to work with a custom database.
