### ISSUE TITLE
What is the point of this line?

### ISSUE THREAD

**Issue by eHealthManny** [auth0/passport-auth0#56]
https://github.com/auth0/passport-auth0/blob/c2efb41e366529b67380e77f036232fa2e85cccd/lib/index.js#L150

I understand the previous line `exports = module.exports = Strategy`, you need to repoint exports at module.exports since module.exports had its reference changed.

But what is the point of `exports.Strategy = Strategy;`, Is this just to give callers two ways to new up a strategy?

ex:
`var auth0Strat = require('passport-auth0)`
 `var firstStrat = new auth0Strat(.....);`
 `var secondStrat = new auth0Strat.Strategy(......)`

**Comment by joshcanhelp** [comment]
This is used in other Passport strategies ([Facebook one here](https://github.com/jaredhanson/passport-facebook/blob/master/lib/index.js#L9)).
