### ISSUE TITLE
logout problems

### ISSUE THREAD

**Issue by dmead** [auth0/passport-auth0#59]
Hi

I'm using this lib with express 4. is there something special i have to do to make logout work? I don't see it in the examples and it seems like standard express stuff isn't actually working. Are there good examples of logout actually removing a session?

**Comment by joshcanhelp** [comment]
There is an example of a logout route in the [Node.js quickstart](https://auth0.com/docs/quickstart/webapp/nodejs#adding-the-authentication-router).

**Comment by eeshugerman** [comment]
so basically this library doesn't support logout out of the box, it needs to be handled manually. [looks like the successor to this library does tho](https://github.com/auth0/express-openid-connect/blob/52f646f8ed48e798020bfaa28450664138407b78/EXAMPLES.md#7-logout-from-identity-provider).
