### ISSUE TITLE
Auth0Strategy vs OAuth2Strategy

### ISSUE THREAD

**Issue by BBaysinger** [auth0/passport-auth0#61]
This tutorial is labelled passport-auth0, but uses OAuth2. In the readme, it mentions Auth0Strategy, but in the code is OAuth2Strategy. I'm confused. Can OAuth2 be substituted for Auth0?

**Comment by joshcanhelp** [comment]
The Auth0 strategy is based on OAuth2 strategy, hence the inheritance.
