### ISSUE TITLE
Unable to verify authorization request state.

### ISSUE THREAD

**Issue by JackPickering** [auth0/passport-auth0#70]
I have not changed anything in my original set up (which worked up until last week). My auth0 strategy is as follows: 

```
	// Perform the login
	app.get('/login',  passport.authenticate('auth0', {
	    clientID: env.AUTH0_CLIENT_ID,
	    domain: env.AUTH0_DOMAIN,
	    redirectUri: env.AUTH0_CALLBACK_URL,
	    audience: env.AUTH0_AUDIENCE,
	    responseType: 'code',
	    scope: 'openid profile'
	  }),
	  function(req, res) {
	    res.redirect('/');
	  }
	);
```

When a user goes to log in, they will be sent to the Auth0s authentication screen. 

It lets me successfully log in to an account, however upon returning to this function:

```
	app.get('/authenticate', passport.authenticate('auth0', { failureRedirect: '/' }, ), 
		function(req, res) {
			console.log('called 4');			
	  	}
	);
```

The failure re-direct is ALWAYS called. Even though when I check my account, it reports that a successful log in has happened. 

So I added the custom call-back to the above function like so:

```
    app.get('/authenticate', passport.authenticate('auth0', function(err, user, info) {
        console.log("authenticate");
        console.log(err);
        console.log(user);
        console.log(info);
    }, { failureRedirect: '/' }, ), 
		function(req, res) {
                    ...
	  	}
    );
```

Which now gives me the response: 

```
authenticate
null
false
{ message: 'Unable to verify authorization request state.' }
```

What does this mean? I cannot find anywhere on the documentation or the community posts that states that on an average authentication method I would need to add a request state.

**Comment by machuga** [comment]
Hi @JackPickering! 

Sorry to hear you're having trouble. I know you mentioned you didn't change anything in your setup, but did you happen to upgrade the version of this repository? Can you let me know what version you're running?

Thanks!

**Comment by homerjam** [comment]
Upgrading 0.6.1 > 1.1.0 introduced silent failures into my otherwise working setup

**Comment by commanderfun** [comment]
I also had this exact issue and was able to fix it by setting the Express Session module's cookie.sameSite option to: false

cookie: { sameSite: false }

**Comment by skoldborg** [comment]
I'm having this exact issue as well, but only when I run my app i with NODE_ENV set to "production". Successful logins shown in the logs on Auth0 but I'm always redirected to my "failureRedirect" path with the same error message as @JackPickering got. 

My auth0 strategy:

`{
        domain: common.auth0.AUTH0_URL,
        clientID: common.auth0.CLIENT_ID,
        clientSecret: common.auth0.CLIENT_SECRET,
        callbackURL: common.auth0.CALLBACK_URL,
        state: true
 }`

**Comment by machuga** [comment]
@skoldborg Did you just upgrade to 1.1.0 from 0.6.x?

**Comment by skoldborg** [comment]
@machuga No, I startwd on 1.1.0. I did try to downgrade to 0.6 though to see if that made a difference. It didn’t, unfortunately.

**Comment by ewarrenG** [comment]
+1

**Comment by chaosmaker** [comment]
Same issue here, had a working authentication and now suddenly it has stopped working. I've noticed that auth0 now sends a state on top of the code authentication...
Anybody got a solution as to how to fix this?

**Comment by chaosmaker** [comment]
> Same issue here, had a working authentication and now suddenly it has stopped working. I've noticed that auth0 now sends a state on top of the code authentication...
> Anybody got a solution as to how to fix this?

Having said this I figured out the solution. 
For those who are still struggling with this here are the two solutions:
a) you turn of state by setting state: false in the Auth0 Strategy setup 
b) 
you leave state: true (or undefined, but it turns out that this is the same)
In my setup I am using csurf in NodeJS to generate a token for CSRF and in my Auth0Lock configuration I had to add auth: { params: { state: csrftoken}} - this token will then get send back by Auth0 so that you can cross reference this. Now at the same time that you send the token to Auth0 you will also have to add it to req.session[key].state = csrftoken. At that point the whole thing should work again. Happy to add some additional code if required.

**Comment by chaosmaker** [comment]
> > Same issue here, had a working authentication and now suddenly it has stopped working. I've noticed that auth0 now sends a state on top of the code authentication...
> > Anybody got a solution as to how to fix this?
> 
> Having said this I figured out the solution.
> For those who are still struggling with this here are the two solutions:
> a) you turn of state by setting state: false in the Auth0 Strategy setup
> b)
> you leave state: true (or undefined, but it turns out that this is the same)
> In my setup I am using csurf in NodeJS to generate a token for CSRF and in my Auth0Lock configuration I had to add auth: { params: { state: csrftoken}} - this token will then get send back by Auth0 so that you can cross reference this. Now at the same time that you send the token to Auth0 you will also have to add it to req.session[key].state = csrftoken. At that point the whole thing should work again. Happy to add some additional code if required.

forgot to mention if you don't set the state variable in your Auth0Lock, Auth0 will generate a random string. The passport-auth0 statestore however will have nothing in it, you could force it to add another random string there too but that would be pointless as the strings won't match.

**Comment by ShayMe21** [comment]
I got this error as well when setting `cookie: { secure: true }` in `express-session` locally. The reason for that is because I was using HTTP and so, the cookie was not being sent to Auth0. If you use a HTTPS connection, this wouldn't be an issue. I fixed it by using https locally and the error is gone.

**Comment by albertoperdomo** [comment]
Can this issue be closed per [comment](https://github.com/auth0/passport-auth0/issues/70#issuecomment-463488935) above?

**Comment by muellermarkus** [comment]
I had the same error (`'Unable to verify authorization request state.'`). 
Trusting the first proxy (my app is behind an nginx reverse proxy) solved it for me:

```
if (process.env.NODE_ENV === 'production') {
  app.set('trust proxy', 1); // trust first proxy
  sess.cookie.secure = true; // serve secure cookies, requires https
}
```

I got the solution from https://www.npmjs.com/package/express-session#cookiesecure

Hope this helps someone! 😊

**Comment by eHealthManny** [comment]
I ran into the same issue: using cookie.secure would case 'Unable to verify authorization request state' to be returned. 

I tracked the error to node_modules/passport-oauth2/lib/state/session.js  
`  req.session[key].state = state;`
This line is trying to save a randomlly generated state value to the current session, this value will eventually be compared to the state value sent from auth0 after the user authenticates. 

In my case the user was getting assigned a new session after being redirected back to my application. Setting saveUninitialized: true solved the issue. This makes express sesssion give the user an empty session immediately after visiting the site. I wonder if there is some type of race condition going on when saveUnitilized: false is used that is causing the temporary session not to be saved?

**Comment by sbubaron** [comment]
Had same issue, this thread was super helpful, but I also found that I needed to add sess.proxy = true

    if (app.get('env') === 'production') {
        sess.cookie.secure = true
        sess.proxy = true
        app.set('trust proxy', 1)
    }

Referencing: https://community.auth0.com/t/redirect-too-many-times/35606/7

**Comment by voinik** [comment]
I ran into the same issue too. Aside from most tips in this thread it turned out my reverse proxy running on Apache wasn't configured appropriately. If you're running an Apache reverse proxy, make sure to add this to your configuration:
```
RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
RequestHeader set X-Forwarded-SSL expr=%{HTTPS}

ProxyPass / http://localhost:8001/
ProxyPassReverse / http://localhost:8001/
```

I've got my working session/cookie configuration posted here: [https://stackoverflow.com/a/67891167/8221175](url)

It turned out my sessions weren't persisting. If you're interested in why you get that (thread title) specific message, check out my answer to this GitHub issue: [https://github.com/auth0/passport-auth0/issues/89#issuecomment-856971807](url)

**Comment by naissa12** [comment]
I'm running into this issue. See here https://stackoverflow.com/questions/71145818/unable-to-verify-authorization-state-on-heroku

I'm running on Heroku and they don't make use of Apache. How can I set the headers 

RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
RequestHeader set X-Forwarded-SSL expr=%{HTTPS}

ProxyPass / http://localhost:8001/
ProxyPassReverse / http://localhost:8001/

in nodejs application? 

@voinik
