### ISSUE TITLE
Not obvious how to style lock on redirect

### ISSUE THREAD

**Issue by mikesol** [auth0/passport-auth0#74]
Hi! I am using auth0 to protect https://app.unmock.io and I am having trouble styling the lock the way I would if I embedded the widget on my own page. Is there any way to pass config options via passport-auth0 (I'm using it in an express app) so that the lock can be styled on the auth0 page before being redirected to my app? Thank you!

**Comment by joshcanhelp** [comment]
We recommend using the Universal Login Page for authentication. [See our docs for a comparison](https://auth0.com/docs/guides/login/universal-vs-embedded).
