### ISSUE TITLE
Export Strategy

### ISSUE THREAD

**Issue by jskrzypek** [auth0/passport-auth0#8]
Many passport modules export the strategy so you can require it like `require('passport-dummyModule').Strategy`, `passport-auth0` should use this method as well.

**Comment by LordZardeck** [comment]
:+1: Having issues integrating this with loopback with this very reason. They assume you will export a `.Strategy` object

**Comment by LordZardeck** [comment]
This should be resolved once they publish the next version, as pr #7 is now merged

**Comment by jfromaniello** [comment]
This was already fixed in #7
