### ISSUE TITLE
too many requests once authenticate under more than 1 instance

### ISSUE THREAD

**Issue by jastsai** [auth0/passport-auth0#86]
Infrastructure:

cloud: aws beanstalk turn on nginx for container proxy server application load balancer - https only, default process (https) 2+ instance in private subnet enabled end to end encryption following https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https-endtoend.html https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance-docker.html

self-signed certificate on instance instance running docker

In local, we have a 3 container to mimic the infrastructure,

1 nginx: 443 as load balancer and https reverse proxy 2 app container: 3000:3000, 3001:3001 respectively so, not end to end encryption yet

software: autho passport (https://github.com/auth0/passport-auth0) express react

workflow: open website, click login link, it then redirect us to auth0 login page, after input username/passport, we click submit.

We are encountering "redirect too many times" when we have more than 1 instance running. The issue goes away if I turn on sticky session on the target group in aws.

We are seeing the same when trying on the local docker environment.

We are not sure why this happens, please advise and help.

**Comment by joshcanhelp** [comment]
@jastsai - Thanks for all the details here. I'm not sure what's going on there. Can you record the process in your Network tab and share that here (minus any sensitive details)? I'd like to see where the redirects bounce between. If you're sending the user to an auth-required page, it could be cached and bouncing back to login, triggering SSO, then back to the callback again.

**Comment by jastsai** [comment]
Issue is resolved, in this cookie config, i made secret as random, now I fixed it to a value so servers can use the same secret.

**Comment by joshcanhelp** [comment]
Are you using `cookie-session` mentioned in #87?

**Comment by jastsai** [comment]
yes, i am. sorry for the late response.
