### ISSUE TITLE
Strategy does not work on Restify

### ISSUE THREAD

**Issue by jayzhou3** [auth0/passport-auth0#96]
Hi, 

I am trying to use passport-auth .0 on my restify app. I knew it works for expressjs. 

Is that possible to have this package works on restify? ????

**Comment by joshcanhelp** [comment]
@jayzhou3 - This strategy is meant to work with Passport so the support there would have to happen in Passport (on an add-on like [this](https://www.npmjs.com/package/passport-restify)). We're currently evaluating options for authentication not using Passport in NodeJS apps.
